services:
  - type: web
    name: taatai-backend
    env: node
    repo: https://github.com/pinequest-2h/taatai-surguuli
    rootDir: backend
    plan: starter  # UPGRADED from free for better performance
    buildCommand: yarn install && yarn build
    startCommand: yarn start -p $PORT
    # Performance optimizations
    healthCheckPath: /api/graphql
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
      - key: ALLOWED_ORIGINS
        value: "http://localhost:3000,https://tuhlag-orchin-eruul-setgel.vercel.app"
      # Add your actual secrets in the Render dashboard or via render CLI
      # - key: MONGODB_URI
      #   sync: false
      # - key: JWT_SECRET
      #   sync: false
      # Email configuration - Add these in Render dashboard
      # - key: SMTP_HOST
      #   value: smtp.gmail.com
      # - key: SMTP_PORT
      #   value: 587
      # - key: SMTP_USER
      #   sync: false
      # - key: SMTP_PASS
      #   sync: false
      # - key: SMTP_FROM
      #   sync: false
