services:
  - type: web
    name: taatai-backend
    env: node
    repo: https://github.com/pinequest-2h/taatai-surguuli
    rootDir: backend
    plan: free
    buildCommand: yarn install && yarn build
    startCommand: yarn start -p $PORT
    envVars:
      - key: NODE_VERSION
        value: 20
      # Add your actual secrets in the Render dashboard or via render CLI
      # - key: MONGODB_URI
      #   sync: false
      # - key: JWT_SECRET
      #   sync: false

